#!/bin/sh

set -e

AGENT=IPaddr2

cleanup () {
  ocft clean $AGENT
}

trap "cleanup" 0 2 3 15

IFACE=$(ip route show 0/0 | cut -d ' ' -f 5)
sed "s/eth0/$IFACE/g" /usr/share/resource-agents/ocft/configs/$AGENT > $AUTOPKGTEST_TMP/$AGENT

mkdir -p /run/resource-agents

ocft make -d $AUTOPKGTEST_TMP $AGENT
ocft test $AGENT
